GMCNEPAL/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls import (
handler400, handler403, handler404, handler500
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# handler404 = 'core.views.page_not_found'



# Translate Route
urlpatterns += i18n_patterns(
    path('e-billing/',include('ebilling.urls',namespace="ebilling")),
    
    
)

core/urls.py
from django.urls import path,include

from .views import *

urlpatterns = [
    path('',homepage,name="homepage")
] 

ebilling/urls.py
from unicodedata import name
from django.urls import path,include

from .views import *



app_name = "ebilling"

urlpatterns = [
    path('login/',loginPage,name='login'),
    path('register/',registerPage),
    path('logout/', Logout),
    path('updateCompanyDetail/',updateCompanyDetailPage,name="updatecompany"),
    path('addClient/',addClientPage,name="addClient"),
    path('clients/',clientsPage,name="clients"),
    path('deleteClient/<int:pk>',deleteClientPage,name='deleteClient'),
    path('updateClient/<int:pk>',updateClientPage,name="updateClient"),
    path('addSupplier/',addSupplierPage,name="addSupplier"),
    path('suppliers/',suppliersPage,name="suppliers"),
    path('deleteSupplier/<int:pk>',deleteSupplierPage,name="deleteSupplier"),
    path('updateSupplier/<int:pk>',updateSupplierPage,name="updateSupplier"),
    path('addExpense/',addExpensePage,name="addExpense"),
    path('expenses/',expensesPage,name="expenses"),
    path('deleteExpense/<int:pk>',deleteExpensePage,name='deleteExpense'),
    path('updateExpense/<int:pk>',updateExpensePage,name="updateExpense"),
    # Master Urls Start Here 
    # path('addBank/',addBank,name="addBank"),
    path('addBank/',addBank,name="addBank"),
    path('deleteBank/',deleteBank,name="deleteBank"),
    path('editBank/',editBank,name="editBank"),
    path('viewBankAccounts/',viewBankAccounts),
    path('adjustBankAccount/<int:pk>',addBankAdjustment),
    path('addExpenseType/',addExpenseType,name="addExpenseType"),
    path('editExpenseType/',editExpenseType,name="editExpenseType"),
    path('deleteExpenseType/',deleteExpenseType,name="deleteExpenseType"),
    path('addDesignation/',addDesignation,name="addDesignation"),
    path('editDesignation/',editDesignation,name="editDesignation"),
    path('deleteDesignation/',deleteDesignation,name="deleteDesignation"),
    path('addDepartment/',addDepartment,name="addDepartment"),
    path('editDepartment/',editDepartment,name="editDepartment"),
    path('deleteDepartment/',deleteDepartment,name="deleteDepartment"),
    path('addUnit/',addUnit,name="addUnit"),
    path('deleteUnit/',deleteUnit,name="deleteUnit"),
    path('editUnit/',editUnit,name="editUnit"),
    path('addBrand/',addBrand,name="addBrand"),
    path('deleteBrand/',deleteBrand,name="deleteBrand"),
    path('editBrand/',editBrand,name="editBrand"),
    path('addGroup/',addGroup,name="addGroup"),
    path('deleteGroup/',deleteGroup,name="deleteGroup"),
    path('editGroup/',editGroup,name="editGroup"),


    path('dashboard/',dashboardPage,name="dashboard"),

    path('companyDetail/',companyDetailPage), # no log messages
    path('category/',categoryPage),# no log messages
    path('category-type/',categoryTypePage),# no log messages
    path('settings/',settingsPage,name="settings"),
    path('taxes/',taxesPage,name="taxes"),
    path('create-update-tax/',createUpdateTax,name="createUpdateTax"),
    path('addProduct/',addProduct,name="addProduct"),
    path('addService/',addService,name="addService"),
    path('deleteService/<int:pk>',deleteService,name="deleteService"),
    path('deleteProduct/<int:pk>',deleteProduct,name="deleteProduct"),
    path('editService/<int:pk>',editService,name="editService"),
    path('editProduct/<int:pk>',editProduct,name='editProduct'),
    path('searchManageProductService/',SearchManageProductAndServicePage,name="searchManageProductService"),
    path('draftPurchase/',draftNewPurchase,name="draftPurchase"),
# Report Link Start here 
    path('reports/clients/amountDueReport',clientAmountDueReport),
    path('reports/suppliers/accountBalanceReport',supplierAccountBalanceReport),
    path('reports/expenses/expensesReport',expensesReport),# no log messages



# Export Links with start from here 
    path('reports/clients/amountDueReport/exportExcel',exportClientDueAmountReportExcel),
    path('reports/clients/amountDueReport/exportPDF',exportClientDueAmountReportPdf),
    path('reports/suppliers/accountBalancesReport/exportExcel',exportSupplierAccountBalancesReportExcel),
    path('reports/expenses/expensesReport/exportExcel',exportExpensesSearchResultReportExcel),
    path('reports/expenses/expensesReport/exportPDF',exportExpensesSearchResultReportPdf),

#Summary Pages Url Here 
    path('summary/stockSummary',StockSummaryPage),




    path('getUserBackup',getUserBackUp),


#Backup and Translation
    path('translation_update/',translation_update),
    path('backup_restore/',backup_restore,name="backup_restore"),
    
    
    path('history/',HistoryView,name="history"),
    
    path('user/',UserView.as_view(),name="user"),
    
    
    
] 

ebilling/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms



class CreateUserForm(UserCreationForm):
    class Meta:
        model= User 
        fields = ['username','email','password1','password2']

ebilling/views.py
from django.views.generic.list import ListView
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404,redirect,reverse
from django.db.models import Count,Q
from django.core.mail import EmailMessage,EmailMultiAlternatives
from django.conf import settings
from django.contrib import messages
from GMCNEPAL.settings import BASE_DIR
from django.utils.translation import gettext as _
from django.contrib.auth.models import Permission
from ebilling.utils import check_permission

from ebilling.models import Category, CategoryType, Company
from .forms import *
from django.contrib.auth import authenticate, login,logout
from django.contrib.auth.decorators import login_required


from django.http import JsonResponse,Http404
# Create your views here.
from django.template.loader import render_to_string

from .models import *
import datetime
from django.template import RequestContext
import xlwt

from django.http import HttpResponse,HttpResponseNotFound
from django.core.files.storage import FileSystemStorage
# Create your views here.

from .utils import Log, render_to_pdf


# Global Variables Start Here 
expensesResultSet=[]
fromDate=""
toDate=""

def setGlobalExpensesResultSet(eResultSet):
    global expensesResultSet    # Needed to modify global copy of globvar
    expensesResultSet = eResultSet

def getGlobalExpensesResultSet():
    return expensesResultSet

def setFromDateAndToDate(fromD,toD):
    global fromDate,toDate
    fromDate=fromD
    toDate=toD 
def getFromDateAndToDate():
    return (fromDate,toDate)

def loginPage(request):
    if request.method == 'POST':
        username=request.POST['username']
        password=request.POST['password']
        user = authenticate(request, username = username, password = password)
        if user is not None:
            form = login(request, user)
            messages.success(request, _("Welcome") + f' {username} !!')
            # print("loggedin")
            return redirect('ebilling:dashboard')
        else:
            messages.error(request, _('account done not exit plz sign in'))
    return render(request,"ebilling/LoginPage.html")


def registerPage(request):
    form=CreateUserForm()
    if request.method == 'POST':
        form=CreateUserForm(request.POST)
        if form.is_valid():
            email=form.cleaned_data.get('email')
            if(len(User.objects.filter(email=email))>0):
                messages.error(request,_("Email already used!!"))
                return redirect(request.META.get('HTTP_REFERER'))
            form.save()
            user=form.cleaned_data.get('username')
            messages.success(request,"Account created for "+user)
            Company(name="N/A",pan_no="N/A",reg_no="N/A",reg_date="N/A",phone="9800000000",city="N/A",district="N/A",province="N/A",pincode="00000",user=request.user,address="N/A").save()

            return redirect('ebilling:login')
    context={'form':form}
    
    return render(request,"ebilling/register.html",context)



@login_required(login_url='/e-billing/login')
@check_permission()
def Logout(request):
    logout(request)
    return redirect('ebilling:login')

@login_required(login_url='/e-billing/login')
@check_permission()
def updateCompanyDetailPage(request):
    if request.method == "POST":
        cid=request.POST['cid']
        if request.FILES:
            logo=request.FILES['logo']    
        name=request.POST.get('name')
        email=request.POST.get('email',None)
        website=request.POST.get('website',None)
        pan_no = request.POST.get('pan_no')
        reg_no = request.POST.get('reg_no',None)
        reg_date = request.POST.get('reg_date',None)
        if(reg_date is not None):
            try:
                reg_date=datetime.datetime.strptime(reg_date, "%d/%m/%Y").strftime("%Y-%m-%d")
            except:
                messages.error(request,_("Date format is incorrect, Eg: dd/mm/yyyy"))
                return redirect("ebilling:updatecompany")
        phone=request.POST.get('phone')
        city=request.POST.get('city')
        district=request.POST.get('district')
        province=request.POST.get('province')
        pincode=request.POST.get('pincode',None)
        address=request.POST.get('address')
        # paper_size=request.POST.get('paper_size')
        try:
            Company(id=cid,name=name,email=email,website=website,pan_no=pan_no,reg_no=reg_no,reg_date=reg_date,phone=phone,city=city,district=district,province=province,pincode=pincode,logo=logo,user=request.user,address=address).save()
        except:
            mylogo=Company.objects.get(id=cid).logo
            Company(id=cid,name=name,email=email,website=website,pan_no=pan_no,reg_no=reg_no,reg_date=reg_date,phone=phone,city=city,district=district,province=province,pincode=pincode,logo=mylogo,user=request.user,address=address).save()
        messages.success(request,_("Company Detail Updated Successfully"))
        return redirect("ebilling:dashboard")
   
    companyObj=Company.objects.filter(user=request.user)[0]
    formattedDate= companyObj.reg_date.strftime("%d/%m/%Y")
    return render(request,"ebilling/UpdateCompanyPage.html",{"company":companyObj,"formattedDate":formattedDate})

@login_required(login_url='/e-billing/login')
@check_permission()
def companyDetailPage(request):
    company= Company.objects.filter(user=User.objects.filter(id=request.user.id)[0])[0]
    print(company)
    if request.method == 'POST':
        tax=request.POST['tax_no']
        if request.FILES:
                logo=request.FILES['logo']    
        name=request.POST['name']
        tax=request.POST['tax_no']
        email=request.POST['email']
        address=request.POST['address']
        phone=request.POST['phone']
       
        company.name=name 
        company.tax_number=tax
        company.email=email
        company.address=address 
        company.phone=phone 
        company.save()
        messages.success(request,"Company Details Updated")
        return redirect('ebilling:dashboard')
       
    if(company):
        context={"company":company}
        return render(request,"ebilling/account-settings.html",context)
    else:
        return render(request,"ebilling/account-settings.html")



@login_required(login_url='/e-billing/login')
@check_permission()
def addClientPage(request):
    if request.method == "POST":
        if request.FILES:
            profile=request.FILES['profile_pic']    
        fullname=request.POST.get('fullname')
        email=request.POST.get('email',None)
        pan_no = request.POST.get('pan_no')
        vat_no = request.POST.get('vat_no',None)
        phone=request.POST.get('phone',None)
        mobile = request.POST.get('mobile')
        city=request.POST.get('city',None)
        district=request.POST.get('district')
        province=request.POST.get('province')
        pincode=request.POST.get('pincode',None)
        billing_address=request.POST.get('billing_address')
        identity_doc_type=request.POST.get('identity_doc',None)
        document_no=request.POST.get('document_no',None)
        account_type=request.POST.get('account_type',None)
        opening_balance=request.POST.get('opening_balance',0)
        credit_allowed=request.POST.get('credit_allowed',None)
        credit_limit=request.POST.get('credit_limit',0)
        remark=request.POST.get('remark',None)
        try:
            Client(fullname=fullname,email=email,mobile=mobile,pan_no=pan_no,
            vat=vat_no,billing_address=billing_address,phone=phone,city=city,
            district=district,province=province,pincode=pincode,
            profile_pic=profile,identity_doc=identity_doc_type,document_no=document_no,account_type=account_type,
            opening_balance=opening_balance,credit_allowed=credit_allowed,credit_limit=credit_limit,
            company=Company.objects.filter(user=request.user)[0],remark=remark).save()
        except:
            Client(fullname=fullname,email=email,mobile=mobile,pan_no=pan_no,
            vat=vat_no,billing_address=billing_address,phone=phone,city=city,
            district=district,province=province,pincode=pincode,
            identity_doc=identity_doc_type,document_no=document_no,account_type=account_type,
            opening_balance=opening_balance,credit_allowed=credit_allowed,credit_limit=credit_limit,
            company=Company.objects.filter(user=request.user)[0],remark=remark).save()
        messages.success(request,"New Client Created :"+str(Client.objects.latest('id').id))
        
        Log(request,f"A New Client has been added, Name:{fullname}; City:{city};")          # Log messages
        
        return redirect("ebilling:clients")
    return render(request,"ebilling/AddClientPage.html")



@login_required(login_url='/e-billing/login')
@check_permission()
def updateClientPage(request,pk):
    client=Client.objects.filter(id=pk,company=Company.objects.filter(user=User.objects.filter(id=request.user.id)[0])[0])[0]
    if request.method == "POST":
        if request.FILES:
            client.profile=request.FILES['profile_pic']    
        client.fullname=request.POST.get('fullname')
        client.email=request.POST.get('email',None)
        client.pan_no = request.POST.get('pan_no')
        client.vat_no = request.POST.get('vat_no',None)
        client.phone=request.POST.get('phone',None)
        client.mobile = request.POST.get('mobile')
        client.city=request.POST.get('city',None)
        client.district=request.POST.get('district')
        client.province=request.POST.get('province')
        client.pincode=request.POST.get('pincode',None)
        client.billing_address=request.POST.get('billing_address')
        client.identity_doc_type=request.POST.get('identity_doc',None)
        client.document_no=request.POST.get('document_no',None)
        client.account_type=request.POST.get('account_type',None)
        client.opening_balance=request.POST.get('opening_balance',0)

templates/ebilling/Blueprint.html
{% extends "ebilling/base.html" %}
{% load i18n %}
{% block title %} {% trans "G-Billing" %} | {% trans "Login" %} {% endblock title %}
{% block content %}



<!--wrapper-->
<div class="wrapper">
   <!--sidebar wrapper -->
   {% include "ebilling/Sidebar.html" %}
   <!--end sidebar wrapper -->
   <!--start header -->
   {% include "ebilling/Header.html" %}
   <!--end header -->
   <!--start page wrapper -->
   <div class="page-wrapper">
      <div class="page-content">

		<!--breadcrumb-->
      <div class="page-breadcrumb d-none d-sm-flex align-items-center mb-3">
         <div class="breadcrumb-title pe-3">{% trans "Forms" %}</div>
         <div class="ps-3">
            <nav aria-label="breadcrumb">
               <ol class="breadcrumb mb-0 p-0">
                  <li class="breadcrumb-item"><a href="javascript:;"><i class="bx bx-home-alt"></i></a>
                  </li>
                  <li class="breadcrumb-item active" aria-current="page">{% trans "Form Layouts" %}</li>
               </ol>
            </nav>
         </div>
 
      </div>
      <!--end breadcrumb-->

   
      </div>
   </div>
   <!--end page wrapper -->
   <!--start overlay-->
   <div class="overlay toggle-icon"></div>
   <!--end overlay-->
   <!--Start Back To Top Button--> <a href="javaScript:;" class="back-to-top"><i class='bx bxs-up-arrow-alt'></i></a>
   <!--End Back To Top Button-->
   {% include "ebilling/Footer.html" %}
</div>
<!--end wrapper-->
<!--start switcher-->
{% include "ebilling/Switcher.html" %}
<!--end switcher-->
<!-- Bootstrap JS -->


{% endblock content %}

templates/ebilling/BrandPage.html
{% extends "ebilling/base.html" %}
{% load i18n %}
{% block title %} {% trans "G-Billing" %} | {% trans "Brands Manangement" %} {% endblock title %}
{% block content %}



<!--wrapper-->
<div class="wrapper">
   <!--sidebar wrapper -->
   {% include "ebilling/Sidebar.html" %}
   <!--end sidebar wrapper -->
   <!--start header -->
   {% include "ebilling/Header.html" %}
   <!--end header -->
   <!--start page wrapper -->
   <div class="page-wrapper">
      <div class="page-content">

		<!--breadcrumb-->
      <div class="page-breadcrumb d-none d-sm-flex align-items-center mb-3">
         <div class="breadcrumb-title pe-3">{% trans "Home" %}</div>
         <div class="ps-3">
            <nav aria-label="breadcrumb">
               <ol class="breadcrumb mb-0 p-0">
                  <li class="breadcrumb-item"><a href="javascript:;"><i class="bx bx-home-alt"></i></a>
                  </li>
                  <li class="breadcrumb-item active" aria-current="page">{% trans "Manage Brands" %}</li>
               </ol>
            </nav>
         </div>
 
      </div>
      <!--end breadcrumb-->
      <div class="card">
         <div class="card-body p-4">
            <h5 class="card-title">{% trans "Existing Brands" %}</h5>
            <hr>
                  <div class="form-body mt-4">
              <div class="row">
                <div class="col-lg-8">
                      <div class="border border-3 p-4 rounded">
                        <table id="unitTable" class="table table-striped table-bordered dataTable" style="width: 100%;"
                        role="grid" aria-describedby="example_info">
                        <thead>
                           <tr role="row">
                              <th class="sorting_asc" tabindex="0" aria-controls="example" rowspan="1" colspan="1"
                                 aria-sort="ascending" aria-label="Name: activate to sort column descending"
                                 style="width: 40px;">{% trans "ID" %}</th>
                              <th class="sorting" tabindex="0" aria-controls="example" rowspan="1" colspan="1"
                                 aria-label="Position: activate to sort column ascending" style="width: 150px;">
                                 {% trans "Brand Name" %}</th>
                                 <th class="sorting" tabindex="0" aria-controls="example" rowspan="1" colspan="1"
                                 aria-label="Position: activate to sort column ascending" style="width: 100px;">
                                 {% trans "Actions" %}</th>

                              


                           </tr>
                        </thead>
                        <tbody id="tBody">

                           {% for t in units %}

                           <tr role="row" class="odd">
                              <td class="sorting_1">#{{t.id}}</td>
                              <td>{{t.name}}</td>
                              <td>
                                 <input type="button" class="btn btn-warning  btn-edit" value='{% trans "Edit" %}' data-sid="{{t.id}}" /> 
                                 <input type="button" class="btn btn-danger  btn-del" value='{% trans "Delete" %}' data-sid="{{t.id}}" />
                                 
                             </td>
                            

                           </tr>
                           {% endfor %}

                        </tbody>
                        <tfoot>
                           <tr>
                              <th rowspan="1" colspan="1">{% trans "ID" %}</th>
                              <th rowspan="1" colspan="1">{% trans "Brand Name" %}</th>
                              <th rowspan="1" colspan="1">{% trans "Actions" %}</th>

                           </tr>
                        </tfoot>
                     </table>
              
                </div>
                </div>
                <div class="col-lg-4">
                  <form method="post" action=".">
                     {% csrf_token %}
                <div class="border border-3 p-4 rounded">
                         <div class="row g-3">
                           <input type="hidden" name="unitId" id="unitId">
                     <div class="col-12">
                      <label for="inputProductTags" class="form-label">{% trans "Brand Name" %}</label>
                      <input type="text" class="form-control" id="unitName"  name="name" placeholder="{% trans "Enter Brand name" %}">
                     </div>
                     <div class="col-12">
                        <label for="inputProductTags" class="form-label">{% trans "Is Enabled" %}</label>
                        <input class="form-check-input" name="is_enabled" type="checkbox" id="isEnabled">
                       </div>
                    

                     <div class="col-12">
                        <div class="d-grid">
                                    <button type="button"   id="btnSave" class="btn btn-light">{% trans "Add" %}</button>
                        </div>
                     </div>
                  </div> 
               </div>
               </form>
               </div>
             </div><!--end row-->
          </div>
         </div>
      </div>
   
      </div>
   </div>
   <!--end page wrapper -->
   <!--start overlay-->
   <div class="overlay toggle-icon"></div>
   <!--end overlay-->
   <!--Start Back To Top Button--> <a href="javaScript:;" class="back-to-top"><i class='bx bxs-up-arrow-alt'></i></a>
   <!--End Back To Top Button-->
   {% include "ebilling/Footer.html" %}
</div>
<!--end wrapper-->
<!--start switcher-->
{% include "ebilling/Switcher.html" %}
<!--end switcher-->
<!-- Bootstrap JS -->



<script src="/static/ebilling/js/jquery.min.js"></script>
<script src="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/alertify.min.js"></script>


<script type="text/javascript">


   $("#btnSave").click(function () {
       output = ""
       let unitId = $("#unitId").val();
       let unitName = $("#unitName").val();
       let isEnabled = $("#isEnabled").is(':checked');
       let csr = $("input[name=csrfmiddlewaretoken").val();
       if (unitName == "") {
           alert("{% trans "Brand Name Can't Be Empty" %}!")
       }
       else {
           mydata = {unitId:unitId, name: unitName, isEnabled: isEnabled, csrfmiddlewaretoken: csr };
           $.ajax({
               url: "{% url 'ebilling:addBrand' %}",
               method: "POST",
               data: mydata,
               success: function (data) {
                   x = data.units;
                   if (data.status == 201) {
                       alertify.set('notifier', 'position', 'top-right');
                       alertify.success("{% trans "New Unit Added" %}");
                       for ( i = 0; i < x.length; i++) {
                           output += `
                           <tr role="row" class="odd">
                              <td> #${x[i].id}</td>
                               <td> ${x[i].name}</td>
                               <td>
                                   <input type="button" class="btn btn-warning btn-edit"  value='{% trans "Edit" %}' data-sid="${x[i].id}" /> 
                                   <input type="button" class="btn btn-danger  btn-del" value='{% trans "Delete" %}' data-sid="${x[i].id}" />
                               </td>
                           </tr>`;
                       }
                   }
                   if (data.status == 200) {
                       alertify.set('notifier', 'position', 'top-right');
                       alertify.success("{% trans "Data Updated" %}");
                       for ( i = 0; i < x.length; i++) {
                           output += `
                           <tr role="row" class="odd">
                              <td># ${x[i].id}</td>
                               <td> ${x[i].name}</td>
                               <td>
                                   <input type="button" class="btn btn-warning  btn-edit" value='{% trans "Edit" %}' data-sid="${x[i].id}" /> 
                                   <input type="button" class="btn btn-danger  btn-del" value='{% trans "Delete" %}' data-sid="${x[i].id}" />
                               </td>
                           </tr>`;
                       }
                   }
                
                   $("#tBody").html(output);
                   $("#unitId").val('');
                   $("form")[0].reset();
                  
                   if (data.status == 400) {
                       alertify.set('notifier', 'position', 'top-right');
                       alertify.error("{% trans "Something went wrong" %}!");
                       $("#unitId").val('');
                       $("form")[0].reset();
                   }
               }

           });
       }
   })

   // Edit Data
   $("#tBody").on("click",".btn-edit",function(){
       let id = $(this).attr("data-sid");
       let csr=$("input[name=csrfmiddlewaretoken").val();
       mydata={sid:id,csrfmiddlewaretoken:csr};
       mythis=this;
       $.ajax({
               url: "{% url 'ebilling:editBrand' %}",
               method: "POST",
               data: mydata,
               dataType:"json",
               success: function (data) {
                  
                   $("#unitId").val(data.id);
                   $("#unitName").val(data.name);
                   if(data.is_enabled == true){
                       $("#isEnabled").prop('checked', true);
                   }
                   
                   if (data.status == 400) {
                       alertify.set('notifier', 'position', 'top-right');
                       alertify.error("{% trans "Something went wrong" %}!");
                   }
                 
               }

           });

   });




   // Delete Data
   $("#tBody").on("click",".btn-del",function(){
       let id = $(this).attr("data-sid");
       let csr=$("input[name=csrfmiddlewaretoken").val();
       mydata={sid:id,csrfmiddlewaretoken:csr};
       mythis=this;
       $.ajax({
               url: "{% url 'ebilling:deleteBrand' %}",
               method: "POST",
               data: mydata,
               success: function (data) {
                   x = data.units;
                   if (data.status == 200) {
                       alertify.set('notifier', 'position', 'top-right');
                       alertify.success("{% trans "Data Deleted" %}!");
                       $(mythis).closest("tr").fadeOut();
                   }
                   if (data.status == 400) {
                       alertify.set('notifier', 'position', 'top-right');
                       alertify.error("{% trans "Something went wrong" %}!");
                   }
               }

           });

   });


</script>


{% endblock content %}

templates/ebilling/base.html
<!DOCTYPE html>
<html class="no-js" lang="">
    {% load i18n %}
<title>{% block title %} {% trans "E-Billing" %} | {% trans "GMC-Nepal" %}{% endblock title %}</title>
{% include "ebilling/Head.html" %}

<body class="bg-theme bg-theme7">
    {% block content %}{% endblock content %}
    {% include "ebilling/Scripts.html" %}
</body>

</html>

templates/ebilling/head.html
<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!--favicon-->
	<link rel="icon" href="/static/ebilling/img/logo-removebg-preview.png" type="image/png" />
	<link href="/static/ebilling/css/bootstrap.min.css" rel="stylesheet">
	<!--plugins-->

	<link href="/static/ebilling/plugins/simplebar/css/simplebar.css" rel="stylesheet" />
	<link href="/static/ebilling/plugins/perfect-scrollbar/css/perfect-scrollbar.css" rel="stylesheet" />
	<link href="/static/ebilling/plugins/metismenu/css/metisMenu.min.css" rel="stylesheet" />
	<link href="/static/ebilling/plugins/highcharts/css/highcharts-white.css" rel="stylesheet" />

	<link href="/static/ebilling/plugins/vectormap/jquery-jvectormap-2.0.2.css" rel="stylesheet" />
	<!-- loader-->
	<link href="/static/ebilling/css/pace.min.css" rel="stylesheet" />
	<script src="/static/ebilling/js/pace.min.js"></script>
	<!-- Bootstrap CSS -->
	<link href="/static/ebilling/css/bootstrap.min.css" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&amp;display=swap" rel="stylesheet">
	<link href="/static/ebilling/css/app.css" rel="stylesheet">
	<link href="/static/ebilling/css/icons.css" rel="stylesheet">
	<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/alertify.min.css" />
	<!-- Default theme -->
	<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/themes/default.min.css" />
	<!-- <link href="/static/ebilling/plugins/datetimepicker/css/classic.css" rel="stylesheet" />
	<link href="/static/ebilling/plugins/datetimepicker/css/classic.time.css" rel="stylesheet" />
	<link href="/static/ebilling/plugins/datetimepicker/css/classic.date.css" rel="stylesheet" />
	<link rel="stylesheet"
		href="/static/ebilling/plugins/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.min.css">
 -->

</head>